name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
   
jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests
    - name: Run tests
      run: swift test --parallel --enable-code-coverage
  xcode:
    runs-on: macos-latest
    strategy:
      matrix:
        scheme: [BigInt-macOS, BigInt-iOS, BigInt-watchOS, BigInt-tvOS]
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: xcrun xcodebuild -workspace BigInt.xcworkspace -scheme ${{ matrix.scheme }}
  linux:
    container:
      image: swift:${{ matrix.linux }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linux: [bionic, xenial, focal]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build --build-tests --enable-test-discovery
    - name: Test
      run: swift test --parallel --enable-test-discovery --enable-code-coverage
  codecov:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test and generate code coverage report
      run: xcrun xcodebuild -workspace BigInt.xcworkspace -scheme BigInt-macOS test
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
